services:
  app:
    image: app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /Users/emmanuelostria/Desktop/Desarrollos/guitarrala:/app
      - /app/node_modules
    stdin_open: true
    tty: true